//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateVault.Models.ADOModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Certificate
    {
        [Key,Column(Order = 0)]
        public string CertificateNumber { get; set; }
        public int VaultId { get; set; }
        [Key,Column(Order = 1)]
        public int MemberID { get; set; }
        [Key,Column(Order = 2)]
        public string SymbolIsin { get; set; }
        public long Volume { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> WithdrawRequestAt { get; set; }
        public string WithdrawRequestBy { get; set; }
        public Nullable<System.DateTime> WithdrawApprovedAt { get; set; }
        public string WithdrawApprovedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Client { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Vault Vault { get; set; }
    }
}
