//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateVault.Models.ADOModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Username { get; set; }
        public string Name { get; set; }
        public string SystemRole { get; set; }
        public string PasswordSalt { get; set; }
        public string EncryptedPassword { get; set; }
        public bool ResetPassword { get; set; }
        public bool AccountActive { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int UserId { get; set; }
    }
}
